//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   無効なログイン試行です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account_Login_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_Login_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なコード。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account_VerifyCode_InvalidCode {
            get {
                return ResourceManager.GetString("Account_VerifyCode_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} の長さは {2} 文字以上である必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_Password_LengthError {
            get {
                return ResourceManager.GetString("ErrorMessage_Password_LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードと確認のパスワードが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_PasswordMissmatch {
            get {
                return ResourceManager.GetString("ErrorMessage_PasswordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいパスワードと確認のパスワードが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage_PasswordMissmatch_New {
            get {
                return ResourceManager.GetString("ErrorMessage_PasswordMissmatch_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号が追加されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_AddPhoneSuccess {
            get {
                return ResourceManager.GetString("Manage_Status_AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが変更されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Status_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_Error {
            get {
                return ResourceManager.GetString("Manage_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインが削除されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("Manage_Status_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号が削除されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_RemovePhoneSuccess {
            get {
                return ResourceManager.GetString("Manage_Status_RemovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが設定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_SetPasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Status_SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 要素認証プロバイダーが設定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_Status_SetTwoFactorSuccess {
            get {
                return ResourceManager.GetString("Manage_Status_SetTwoFactorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号を確認できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Manage_VerifyPhoneNumber_Failed {
            get {
                return ResourceManager.GetString("Manage_VerifyPhoneNumber_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_Code {
            get {
                return ResourceManager.GetString("Property_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のパスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_CurrentPassword {
            get {
                return ResourceManager.GetString("Property_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電子メール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_EMail {
            get {
                return ResourceManager.GetString("Property_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいパスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_NewPassword {
            get {
                return ResourceManager.GetString("Property_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいパスワードの確認入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_NewPasswordConfirm {
            get {
                return ResourceManager.GetString("Property_NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_Password {
            get {
                return ResourceManager.GetString("Property_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの確認入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_PasswordConfirm {
            get {
                return ResourceManager.GetString("Property_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_PhoneNumber {
            get {
                return ResourceManager.GetString("Property_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証情報をこのブラウザーに保存しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_RememberBrowser {
            get {
                return ResourceManager.GetString("Property_RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアカウントを記憶する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Property_RememberMe {
            get {
                return ResourceManager.GetString("Property_RememberMe", resourceCulture);
            }
        }
    }
}
